server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Auth Service
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1

        # Affiliates Service
        - id: affiliate-service
          uri: lb://affiliate-service
          predicates:
            - Path=/affiliate-service/**
          filters:
            - StripPrefix=1

        # Medical Coverage Service
        - id: medical-coverage-service
          uri: lb://medical-coverage-service
          predicates:
            - Path=/medical-coverage-service/**
          filters:
            - StripPrefix=1

        # Appointments Service
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointment-service/**
          filters:
            - StripPrefix=1

        # Dental Service
        - id: dental-service
          uri: lb://dental-service
          predicates:
            - Path=/dental-service/**
          filters:
            - StripPrefix=1

        # Employee Service
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee-service/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}

internal:
  secret: ${INTERNAL_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized